### ISSUE TITLE
HACS

### ISSUE THREAD

**Issue by alnavasa** [dangreco/threedy#11]
Waiting until it is HACS installable/updatable, Will this be one day?

**Comment by Jan-Ka** [comment]
`hacs.json` is done, if the next release has files with the correct name (hacs wants https://github.com/dangreco/threedy/blob/a516447bf721f792486ad28b5a74797d10373df3/hacs.json#L5 but gets `bundle.js`) it should work.

Also the Repository needs Topics as per https://hacs.xyz/docs/publish/start#topics

Ping @dangreco

**Comment by dangreco** [comment]
I've added the topics to the repo! The next release will indeed be following the ```threedy-card.js``` naming scheme. As far as when the next release is, I'm trying to ship out the graphical card configuration element as soon as possible. I've been testing multiple react component libraries trying to find one that is lightweight and compatible with the shadow DOM. ETA for the next release is 11:59PM (EST) on Sunday, Jan 31st. Stay tuned!!

**Comment by Jan-Ka** [comment]
Thanks for the quick work!

**Comment by Jan-Ka** [comment]
Ping @dangreco 

Found something else :(

My test for https://github.com/dangreco/threedy/pull/14 worked because I hadn't marked my test-release as pre-release.
As far as my tests show, you need at least one "real" release to be able to load the repository in HACS (at which point you can select "BETA" in the Install Modal)

![image](https://user-images.githubusercontent.com/11042838/106402358-6b34ef00-6429-11eb-8f42-2f5ce8a05bd6.png)

https://github.com/Jan-Ka/threedy/releases/tag/2021.0.b1b is my test pre-release
https://github.com/Jan-Ka/threedy/releases/tag/2021.0.b1 is the previous test release

If I swap the first release to pre-release, I won't be able to add it again. Seems like a bug in HACS (or at least something that the user should be able to force through).

You could just release the first release as "initial release" as that would also have a file of the correct name. Just a suggestion.
Otherwise, we just have to wait until you make your first release.

**Comment by dangreco** [comment]
I'm going to push out the first stable release asap -- I want to quickly implement a full graphical config for all options before release. Glad to know it works otherwise though!

**Comment by dannytsang** [comment]
Managed to add this via HACS. The base git clone url doesn't seem to work until I used the links above: https://github.com/Jan-Ka/threedy/releases/tag/2021.0.b1b so can I suggest if I am adding the repo wrong or add it to the README?

**Comment by apoc4lyps** [comment]
I think it's because there are only pre-release tags. @dangreco is there any plan for a release in the future?
Btw, thanks for the work, great card.

**Comment by dangreco** [comment]
> I think it's because there are only pre-release tags. @dangreco is there any plan for a release in the future?
> Btw, thanks for the work, great card.

Yep, release coming soon! Been swamped with uni course work but gonna get around to finishing the initial release by this next weekend.

**Comment by dangreco** [comment]
Should be available via HACS now that there is a release!

**Comment by luisleonardo** [comment]
I can't find it on HACS. I've searched for threedy, 3D and printer and no matching results.

**Comment by Jan-Ka** [comment]
@luisleonardo it is not published to HACS, but you can add it as custom repository using this repo's URL now.

as per https://hacs.xyz/docs/publish/include
> Only the owner of the repository or a major contributor to it can submit a PR to have it included as a default.

**Comment by luisleonardo** [comment]
And what's the correct link? Because the repo's URL gave me this message:
Repostitory structure for 2021.0.1 is not compliant

**Comment by apoc4lyps** [comment]
I tried with https://github.com/dangreco/threedy and it works as expected.

**Comment by luisleonardo** [comment]
I restarted HA and now it works. Thanks.

**Comment by dannytsang** [comment]
I was able to add it successfully. Thanks @dangreco !
