### ISSUE TITLE
Request: Add temperature and humidity sensor for enclosure

### ISSUE THREAD

**Issue by Sim7b** [dangreco/threedy#13]
Hi !
Thanks for your card, it could be nice to have an option to add my own sensor of temperature and humidity of the enclosure like it's an important information.
Thanks !!

**Comment by dangreco** [comment]
Hey! Thanks for the interest and support!

I probably won't make this a native feature since there is no direct enclosure temp -> octoprint -> home assistant path (reading on the forms seems to show that it's a curl command you run to fetch the temps). 

However, due to the fact that there now have been requests for stats that I don't want to necessarily make native, I'm pretty sure I'll include the ability to use a custom entity as a stat in the future. (Ping @giuliandenicola1 -- you might be interested in this too!)
